server:
  port: 9001       #  9001
spring:
  application:
    name: dynamiczuul   #最后读的是github上的  dynamiczuul-dev.yml  只有路由放在git上动态路由
    #处理中文乱码
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
#商品服务路由
zuul:
  routes:
    #路由服务2--product-server
    product-server:
      path: /product/gateway/**
      #普通路由
      #url: http://localhost:2100/
      #面向服务
      serviceId: product-server  #http://localhost:9001/api/product-gateway/products
    #路由服务2--consumer-service
    consumer-service:
      path: /consumer/gateway/**
      serviceId: consumer-service
  #      http://localhost:9001/api/consumer/gateway/products?username=zhangning
  #zuul通用配置
  prefix: /api     #前缀
  retryable: true  #开启路由重试
  ignored-services: "*"  #zuul默认为所有服务开启默认的路由，为了服务安全，此处关闭  *就是忽略所有服务

# 开放监控端口
management:
  endpoints:
    web:
      exposure:
        # 配置刷新地址：POST http://127.0.0.1:9000/actuator/refresh
        include: "*"
webconfig:
  nname: zhanghaining-xiugai001
